spring:
  main.banner-mode: "off"
  output.ansi.enabled: always

authentication:
  access_token_validity_seconds: 5
  refresh_token_validity_seconds: 5

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
